# version-file which will write or read current semver
version = 1.0

# hook scripts
[hooks]

# git hook pre commit
pre-commit = [
    "husky lint-staged",
]

# git hook commit msg
commit-msg = [
    "husky lint-commit",
]

# list staged files do some pre-process and git add
[lint-staged]
"*.go" = [
    "gofmt -l -w",
]

# commit msg rule default support conventional commits
[lint-commit]
# could check if this exists
# email = ".*"
# optional custom types check regex
types = "^(feat|fix|build|chore|ci|docs|perf|cleanup|refactor|revert|style|test|release)$"
# optional header check regex
# header = "^(?P<type>\w+)(\((?P<scope>[\w/.-]+)\))?(?P<breaking>!)?:( +)?(?P<header>.+)"